name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18.x, 20.x]
        command: ['lint', 'format', 'test:integration', 'build']
    steps:
      - uses: actions/checkout@v4

      - name: Set Up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable --immutable-cache

      - run: yarn ${{ matrix.command }}
